using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stalker.StalkerRepository.RepositorySlider;
[GenerateTypedNameReferences]
public sealed partial class RepositorySlider : DefaultWindow
{
    public event Action? ConfirmButtonPressed;
    public RepositorySlider(int maxValue)
    {
        RobustXamlLoader.Load(this);

        CountSlider.MaxValue = maxValue;

        ConfirmButton.OnPressed += _ =>
        {
            ConfirmButtonPressed?.Invoke();
            Close();
        };
    }

    public int GetSliderValue()
    {
        return CountSlider.Value;
    }
}
