using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stalker.StalkerUi.Widgets;

[GenerateTypedNameReferences]
public sealed partial class PsyGui : UIWidget
{
    public PsyGui()
    {
        RobustXamlLoader.Load(this);
        LayoutContainer.SetGrowVertical(this, LayoutContainer.GrowDirection.Begin);

        PsyTexture.TexturePath = "/Textures/_Stalker/Interface/Icons/psy_ball/psy.png";
    }

    public void UpdatePanelEntity(int currentPsy, int maxPsy)
    {
        if (maxPsy == 0)
        {
            PsyContent.Visible = false;
            return;
        }

        PsyContent.Visible = true;
        var psyNumbers = $"{currentPsy} / {maxPsy}";
        PsyNumbersLabel.Text = psyNumbers;
    }
}
