- type: entity
  parent: BaseItem
  id: STBaseWeaponGameRevolver
  name: STBaseWeaponGameRevolver
  description: A rooty tooty point and shooty.
  suffix: ST, Revolver, револьвер
  abstract: true
  components:
  - type: FarGunshot
    range: 170
    sound: /Audio/_DZ/Effects/FarGunshots/pistol1.ogg
  - type: Sprite
    state: icon
  - type: Item
    size: Small
    shape:
    - 0,0,1,0
    - 0,1,0,1
  - type: RepositoryItem
    categoryName: Оружие
  - type: Tag
    tags:
    - Sidearm
  - type: Clothing
    sprite: Objects/Weapons/Guns/Revolvers/deckard.rsi
    quickEquip: false
    slots:
    - suitStorage
    - Belt
  - type: Gun
    selectedMode: SemiAuto
    fireRate: 1.5
    availableModes:
    - SemiAuto
    soundGunshot:
      path: /Audio/Weapons/Guns/Gunshots/revolver.ogg
  - type: UseDelay
    delay: 0.66
  - type: ContainerContainer
    containers:
      revolver-ammo: !type:Container
  - type: RevolverAmmoProvider
    whitelist:
      tags:
        - CartridgeMagnum
        - SpeedLoaderMagnum
    proto: Null
    capacity: 6
    chambers: [ True, True, True, True, True, True ]
    ammoSlots: [ null, null, null, null, null, null ]
    soundEject:
      path: /Audio/Weapons/Guns/MagOut/revolver_magout.ogg
    soundInsert:
      path: /Audio/Weapons/Guns/MagIn/revolver_magin.ogg
  - type: StaticPrice
    price: 1
