- type: entity
  id: BaseShippingContainer
  abstract: true
  placement:
    mode: SnapgridCenter
  components:
  - type: SpriteFade
  - type: Clickable
  - type: Sprite
    sprite: Corvax/Objects/Decoration/containers.rsi
    netsync: false
    drawdepth: Overdoors
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,0,1.5,-1"
        density: 1000
        layer:
        - WallLayer
  - type: Damageable
    damageContainer: Inorganic
    damageModifierSet: Metallic
  - type: Destructible
    thresholds:
      - trigger:
          !type:DamageTrigger
          damage: 500
        behaviors:
          - !type:SpawnEntitiesBehavior
            spawn:
              CraftSheetSteel:
                min: 0
                max: 1
              CraftSheetIron:
                min: 0
                max: 1
              CraftSheetAluminum:
                min: 0
                max: 1
              CraftScrap:
                min: 0
                max: 1
              CraftRubber:
                min: 0
                max: 1
              CraftMetalParts:
                min: 0
                max: 1
              PartRodMetalStalker:
                min: 0
                max: 1
          - !type:PlaySoundBehavior
            sound:
              collection: MetalBreak
          - !type:DoActsBehavior
            acts: [ "Destruction" ]
