using System.Text.RegularExpressions;
using Content.Client.UserInterface.Controls;
using Content.Shared._Stalker.RadioStalker;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stalker.RadioStalkerUi;

[GenerateTypedNameReferences]
public sealed partial class RadioStalkerMenu : FancyWindow
{

    public event Action<bool>? OnMicPressed;
    public event Action<bool>? OnSpeakerPressed;
    public event Action<string>? InputTextEntered;

    public RadioStalkerMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        MicButton.OnPressed += args =>
        {
            OnMicPressed?.Invoke(args.Button.Pressed);
            SpeakerButton.Pressed = false;
        };
        SpeakerButton.OnPressed += args =>
        {
            OnSpeakerPressed?.Invoke(args.Button.Pressed);
            MicButton.Pressed = false;
        };
        ChannelInput.OnTextEntered += args => InputTextEntered?.Invoke(args.Text);
    }

    public void Update(RadioStalkerBoundUIState state)
    {
        MicButton.Pressed = state.MicEnabled;
        SpeakerButton.Pressed = state.SpeakerEnabled;
        ChannelInput.Text = state.CurrentFrequency ?? string.Empty;
    }
}
