using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stalker.Shop.Ui.SliderTab;

[GenerateTypedNameReferences]
public sealed partial class ShopSlider : DefaultWindow
{
    public event Action? ConfirmButtonPressed;
    private readonly int _pricePerUnit;
    public ShopSlider(int maxValue, int pricePerUnit)
    {
        RobustXamlLoader.Load(this);

        _pricePerUnit = pricePerUnit;

        CountSlider.MaxValue = maxValue;
        CountSlider.OnValueChanged += UpdatePrice;

        ConfirmButton.OnPressed += _ =>
        {
            ConfirmButtonPressed?.Invoke();
            Close();
        };

        UpdatePrice(CountSlider.Value);
    }

    private void UpdatePrice(int value)
    {
        PriceLabel.Text = Loc.GetString("shop-selling-price", ("amount", (value * _pricePerUnit).ToString()));
    }

    public int GetSliderValue()
    {
        return CountSlider.Value;
    }
}
