using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stalker.RadioStalkerUi.EncryptionKeyUi;

[GenerateTypedNameReferences]
public sealed partial class ConfigurableEncryptionKeyMenu : FancyWindow
{
    public event Action<string>? ChannelInputEntered;

    public ConfigurableEncryptionKeyMenu()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        ChannelInput.OnTextEntered += args => ChannelInputEntered?.Invoke(args.Text);
    }
}
