using Content.Shared._Stalker.StalkerRepository;
using Robust.Client.AutoGenerated;
using Robust.Client.Graphics;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stalker.StalkerRepository;
[GenerateTypedNameReferences]
public sealed partial class StalkerRepositoryItemControl : Control
{
    public RepositoryItemInfo ItemInfo;
    private Texture? _itemTexture;
    private int _nameLength = 19;
    public StalkerRepositoryItemControl(RepositoryItemInfo item, Texture? texture)
    {
        RobustXamlLoader.Load(this);
        ItemInfo = item;
        _itemTexture = texture;
        var name = item.Name;
        if (name.Length > _nameLength)
        {
            name = item.Name[.._nameLength] + "..";
        }
        ItemName.Text = item.Count == 1 ? name : $"{name}\n{item.Count} шт.";
        SelectButton.Text = "Выбрать";
        SelectButton.ToggleMode = true;

        ItemTexture.Texture = _itemTexture;

    }
}
