- type: entity
  abstract: true
  parent: STBaseWeaponGun
  id: STBaseWeaponRifle
  name: A rifle
  components:
  - type: Sprite
    layers:
    - state: base
      map: ["enum.GunVisualLayers.Base"]
    - state: mag-0
      map: ["enum.GunVisualLayers.Mag"]
    - state: muzzle
      map: ["enum.GunVisualLayers.Muzzle"]
    - state: scope
      map: ["enum.GunVisualLayers.Scope"]
  - type: Wieldable
  - type: GunWieldBonus
    minAngle: -40
    maxAngle: -40
  - type: PullDoAfter
    pullTime: 2.5
  - type: Gun
    projectileSpeed: 60
    selectedMode: FullAuto
    availableModes:
    - SemiAuto
    - FullAuto
  - type: ChamberMagazineAmmoProvider
    soundRack:
      path: /Audio/_Stalker/Weapons/Guns/RifleGen/Cock/rifle_cock.ogg
  - type: ContainerContainer
    containers:
      gun_magazine: !type:ContainerSlot
      gun_module_muzzle: !type:ContainerSlot
      gun_module_scope: !type:ContainerSlot
      gun_chamber: !type:ContainerSlot
