- type: entity
  abstract: true
  parent: STBaseWeaponGun
  id: STBaseWeaponSniper
  name: sniper
  description: A rooty tooty point and shooty.
  suffix: Weapon, Sniper
  components:
  - type: Sprite
    layers:
    - state: base
      map: ["enum.GunVisualLayers.Base"]
    - state: mag-0
      map: ["enum.GunVisualLayers.Mag"]
    - state: muzzle
      map: ["enum.GunVisualLayers.Muzzle"]
    - state: sight
      map: ["enum.GunVisualLayers.Scope"]
  - type: Item
    size: Large
    shape:
      - 0,0,7,1
  - type: Wieldable
  - type: GunWieldBonus
    minAngle: -50
    maxAngle: -50
  - type: RepositoryItem
    categoryName: Оружие
  - type: Clothing
    sprite: Objects/Weapons/Guns/Snipers/bolt_gun_wood.rsi
    quickEquip: false
    slots:
    - Back
    - suitStorage
  - type: AmmoCounter
  - type: Gun
    projectileSpeed: 75
    fireRate: 0.75
    selectedMode: SemiAuto
    availableModes:
    - SemiAuto
    soundGunshot:
      path: /Audio/Weapons/Guns/Gunshots/sniper.ogg
  - type: ContainerContainer
    containers:
      ballistic-ammo: !type:Container
        ents: []
      gun_module_scope: !type:ContainerSlot
      gun_module_muzzle: !type:ContainerSlot
  - type: PullDoAfter
    pullTime: 3.5
  - type: ChamberMagazineAmmoProvider
    soundRack:
      path: /Audio/_Stalker/Weapons/Guns/RifleGen/Cock/rifle_cock.ogg
  - type: STWeaponModuleContainer
  - type: ItemSlots
    slots:
      gun_module_scope:
        name: Scope
        priority: 2
        whitelist:
          tags:
            - STWeaponModuleSniperSight
      gun_module_muzzle:
        name: Muzzle
        priority: 1
        whitelist:
          tags:
            - STWeaponModuleSniperSilencer
  - type: Scope
    zoom: 1.3
    delay: 1
    requireWielding: true
    offset: 9
    useInHand: false
