using Content.Shared._Stalker.PdaMessenger;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stalker.PdaMessenger;

[GenerateTypedNameReferences]
public sealed partial class MessengerUiMessage : BoxContainer
{
    public MessengerUiMessage(PdaMessage message)
    {
        RobustXamlLoader.Load(this);

        Title.Text = message.Title;
        Content.SetMessage(message.Content);
    }
}
