using Content.Shared._Stalker.PdaMessenger;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stalker.PdaMessenger;

[GenerateTypedNameReferences]
public sealed partial class MessengerUiChat : BoxContainer
{
    public MessengerUiChat(PdaChat chat)
    {
        RobustXamlLoader.Load(this);

        Name.Text = chat.Name;
    }
}
