using Robust.Client.AutoGenerated;
using Robust.Client.Console;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client._Stalker.Discord;

[GenerateTypedNameReferences]
public sealed partial class DiscordAuthGui : Control
{
    [Dependency] private readonly IClientConsoleHost _consoleHost = default!;
    [Dependency] private readonly DiscordAuthManager _discordAuthManager = default!;

    public DiscordAuthGui()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        LayoutContainer.SetAnchorPreset(this, LayoutContainer.LayoutPreset.Wide);

        var link = _discordAuthManager.AuthLink;

        AuthLinkEdit.SetText(link);
        DLinkEdit.SetText(DiscordAuthManager.DiscordServerLink);
        InfoLabel.SetMessage(Loc.GetString("stalker-discord-info"));

        ErrorMessage.SetMessage(_discordAuthManager.ErrorMessage);

        var uriOpener = IoCManager.Resolve<IUriOpener>();

        QuitButton.OnPressed += _ =>
        {
            _consoleHost.ExecuteCommand("disconnect");
        };

        AuthorizeButton.OnPressed += _ =>
        {
            uriOpener.OpenUri(link);
        };

        DiscordButton.OnPressed += _ =>
        {
            uriOpener.OpenUri(DiscordAuthManager.DiscordServerLink);
        };
    }
}
